import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        headline: ["var(--font-noto-serif)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      colors: {
        "on-secondary-fixed-variant": "#3a4953",
        "on-secondary": "#ffffff",
        "tertiary": "#6e5659",
        "primary-fixed-dim": "#ffb2bc",
        "secondary-container": "#d2e2ee",
        "secondary-fixed-dim": "#b9c9d5",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#0e1d26",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#70343e",
        "on-tertiary-fixed-variant": "#574144",
        "surface-tint": "#8c4b55",
        "on-primary-container": "#fffbff",
        "tertiary-fixed": "#fbdbde",
        "on-error-container": "#93000a",
        "primary-container": "#a6606b",
        "tertiary-fixed-dim": "#debfc2",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-highest": "#e2e2e2",
        "surface": "#f9f9f9",
        "error": "#ba1a1a",
        "on-secondary-container": "#55656f",
        "on-surface": "#1a1c1c",
        "on-background": "#1a1c1c",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed": "#281719",
        "surface-container-high": "#e8e8e8",
        "tertiary-container": "#886e71",
        "on-primary-fixed": "#3a0915",
        "on-surface-variant": "#524345",
        "inverse-primary": "#ffb2bc",
        "surface-dim": "#dadada",
        "background": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "primary-fixed": "#ffd9dd",
        "outline": "#857374",
        "on-tertiary": "#ffffff",
        "secondary": "#51606b",
        "on-tertiary-container": "#fffbff",
        "primary": "#8a4853",
        "surface-container": "#eeeeee",
        "outline-variant": "#d7c1c3",
        "secondary-fixed": "#d5e5f1",
        "inverse-surface": "#2f3131",
        "surface-variant": "#e2e2e2"
      },
    },
  },
  plugins: [],
};
export default config;
